env:
  browser: true
  es2021: true
  node: true
  commonjs: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react-hooks/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
parser: babel-eslint
rules:
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
  jsx-a11y/anchor-is-valid:
    - error
    - components:
      - Link
      specialLink:
      - hrefLeft
      - hrefRight
      aspects:
      - invalidHref
      - preferButton
globals:
  React: writable
settings:
  react:
    version: detect
